apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplebank
  labels:
    app: simplebank
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simplebank
  template:
    metadata:
      app: simplebank
    spec:
      containers:
        - name: simplebank
          image:
          ports:
            - containerPort: 8080
